### ISSUE TITLE
[problem] Unexpected White Cubes in Generated Image After Inpainting Process

### ISSUE THREAD

**Issue by geonhak904** [Sealical/anywhere-multi-agent#3]
Hi, First of all, thank you for your contribution to your work.

I’m delightfully enjoying your code. However, in some cases, I’ve encountered a problem related to the generation of meaningless white boxes/cubes. After using the SDXLControlNet pipeline with an alpha image, the images are generated well, and I have confirmed this.

However, after running the inpainting pipeline, the generated image contains meaningless white boxes/cubes, even though the prompt is unrelated. Have you experienced the same issue?

It doesn't change whether I use an LLM prompt, or change/add negative prompts like "white box," "white background," etc.

I'll show you some examples (coffee, puppy).

## example 1 coffee

**inpainting**

![coffee-2306471_1280_alpha_alpha_center_before_20240904_0530_18](https://github.com/user-attachments/assets/f9133802-b30d-45e2-bff4-e763c81a7d83)
![coffee-2306471_1280_alpha_alpha_center_before_20240904_0530_22](https://github.com/user-attachments/assets/772ebb85-8402-44e8-848e-a8c3d6a2b1f8)

![coffee-2306471_1280_alpha_alpha_center_before_20240904_0530_28](https://github.com/user-attachments/assets/3f7c6846-2be5-43c8-bb51-cc92acdbc788)

**refine (final results)**
![coffee-2306471_1280_alpha_alpha_center_edit_20240904_0530_19](https://github.com/user-attachments/assets/ada3ece3-8a2d-4c4b-bfdd-9e1103ada349)
![coffee-2306471_1280_alpha_alpha_center_edit_20240904_0530_23](https://github.com/user-attachments/assets/b416ae71-3533-4d53-90c7-0264af7db048)
![coffee-2306471_1280_alpha_alpha_center_edit_20240904_0530_29](https://github.com/user-attachments/assets/a1e29b5a-7ee3-4baf-8ab8-196b9408518c)

## example 2 puppy

**controlnet**
![puppy-1903313_1280_alpha_alpha_center_alpha_controlnet_20240904_0941_3](https://github.com/user-attachments/assets/3181ec13-9f29-4481-b9fc-e49c124f10fb)
![puppy-1903313_1280_alpha_alpha_center_alpha_controlnet_20240904_0941_5](https://github.com/user-attachments/assets/b6ae50ab-210d-435d-ad14-f83960542b13)
![puppy-1903313_1280_alpha_alpha_center_alpha_controlnet_20240904_0941_11](https://github.com/user-attachments/assets/b5d52861-b494-4abe-b5b5-b9a440c5d8ce)

**inpainting**
![puppy-1903313_1280_alpha_alpha_center_alpha_before_20240904_0941_6](https://github.com/user-attachments/assets/b3c12134-6c47-49f3-9ad6-7392d3d3d319)
![puppy-1903313_1280_alpha_alpha_center_alpha_before_20240904_0941_10](https://github.com/user-attachments/assets/ef0eb597-19a6-417b-a1c9-346bf6d605ee)
![puppy-1903313_1280_alpha_alpha_center_alpha_before_20240904_0941_22](https://github.com/user-attachments/assets/cd867f20-ab8e-497f-9f61-30392f960f6c)

**refine (final results)**

![puppy-1903313_1280_alpha_alpha_center_alpha_edit_20240904_0941_7](https://github.com/user-attachments/assets/f291299a-5628-4d42-b0e6-5a97928c958d)
![puppy-1903313_1280_alpha_alpha_center_alpha_edit_20240904_0941_11](https://github.com/user-attachments/assets/1beaaeb1-e4d6-445f-b621-303428110fdb)
![puppy-1903313_1280_alpha_alpha_center_alpha_edit_20240904_0941_23](https://github.com/user-attachments/assets/d75ee009-9e99-4dc1-be56-4cf883db7ec5)

**Comment by Sealical** [comment]
Thank you for your interest in our work. The main reasons for the white box appearing are:

1. We used a simple RMBG model to remove the background, but in reality, this doesn't guarantee satisfactory results every time (it may include more irrelevant areas). A better approach would be to use Grounding-SAM2 for this task.
2. The inpainting model "overfills" the content in the imagined areas. You can reduce the occurrence of this situation in the following ways:

a. Modify the `fixUnoverlapArea` function in `product2Image.py`: Change `max_depth=2, num_per_prompt=2, unoverlap_rate_th=0.03` to `max_depth=1, num_per_prompt=2, unoverlap_rate_th=0.1`. This means that if an imagined area is detected (occupying more than 10% of the original foreground, indicating a higher tolerance for imagined areas), it will attempt to generate 2 images once.

b. Change the inpainting model (in the repainting agent) from SDXL inpainting to other models that focus on filling backgrounds, such as LaMa or ZITS. These models are faster and less likely to generate additional content.

We have improved and reorganized the code and models since the release of this version. A new version of the code will be available online soon.

**Comment by geonhak904** [comment]
Thank you for replying super so fast!!!

I appreciate that.

I’ll proceed with the grounding sam2 and the correction method as you mentioned. Thank you.
